name: medinix_frontend
description: "Medinex is a full-stack healthcare management platform with a Flutter-based mobile frontend and a Node.js serverless backend."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  http: ^1.3.0
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  qr_flutter: ^4.1.0
  encrypt: ^5.0.3
  smooth_page_indicator: ^1.2.1
  web_socket_channel: ^3.0.2
  permission_handler: ^12.0.0+1
  mobile_scanner: ^6.0.7
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/pngs/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
